# Generated by Django 3.1.1 on 2020-12-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='total_envios',
            field=models.IntegerField(null=True),
        ),
    ]
