# Generated by Django 3.1.1 on 2020-10-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20201016_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='nombre',
            new_name='nombre_estado',
        ),
        migrations.RenameField(
            model_name='evidencia',
            old_name='logo',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='historial',
            new_name='nombre_historial',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='campo_res',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='campo_res',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='campo_res',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='campo_reserva',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='campo_res',
        ),
    ]
